# Define CI/CD stages
stages:
  - build
  - test

# Build stage
build:
  stage: build
  script:
    - echo "Building project..."
    - mkdir -p build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build/  # Save build artifacts for debugging if needed

# Test stage
test:
  stage: test
  script:
    - echo "Running tests..."
    - mkdir -p build
    - cd build
    - cmake ..
    - make
    - ctest --output-on-failure
  dependencies:
    - build  # Ensure the build job runs before tests
