# .gitlab-ci.yml

stages:
  - build
  - test

variables:
  BUILD_DIR: "backend/build"  # Directory where build outputs will be stored

build_job:
  stage: build
  image: gcc:latest

  before_script:
    # Install required build tools
    - apt-get update && apt-get install -y make g++ git

  script:
    # Step 1: Build the project using Makefile
    - mkdir -p $BUILD_DIR
    - make -C backend  # Adjust path if Makefile is located elsewhere

  artifacts:
    paths:
      - backend/build/

test_job:
  stage: test
  image: gcc:latest

  before_script:
    # Install required build tools (if not carried over from build_job)
    - apt-get update && apt-get install -y make g++ git

  script:
    # Run tests, assuming `make test` is set up in your Makefile
    - make -C backend test
